const SERVICE_TYPES = {
  MEDICINE: "MEDICINE",
  LAB: "LAB",
  DOCTOR: "DOCTOR",
  PHYSIO: "PHYSIO",
  RADIOLOGY: "RADIOLOGY",
  SUPPORT: "SUPPORT"
};

const REQUEST_STATUS = {
  PENDING: "PENDING",
  AWAITING_QUOTES: "AWAITING_QUOTES",
  AWAITING_USER_SELECTION: "AWAITING_USER_SELECTION",
  LOCKED: "LOCKED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
};

const USER_STATE = {
  NEW: "NEW",
  IDLE: "IDLE",
  AWAITING_SERVICE_SELECTION: "AWAITING_SERVICE_SELECTION",
  AWAITING_SERVICE_DETAILS: "AWAITING_SERVICE_DETAILS",
  AWAITING_QUOTE_SELECTION: "AWAITING_QUOTE_SELECTION",
  AWAITING_DOCTOR_SELECTION: "AWAITING_DOCTOR_SELECTION"
};

module.exports = {
  SERVICE_TYPES,
  REQUEST_STATUS,
  USER_STATE
};
